---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAUiC8EEVteM44hzPGLtCJ+v2BMzL4UQlYDkVYPO4ASSUZq8yZTKJWyeZAl2opTEk8lk+KaR93fQ6qSJKv2gGrOPWUOzz6s6qWgrMSplYwq3BwtCeolPLMxvA7ojhr3XCsi/1jVC7AeFsqHHu79tYqd9oRpYpu+ZPWXOPQzmnwKrdWB/5mk00lWcOAagU/X3sd7tZMNsT+wfnSgmo4E49ntzD/6fYvC83P+yzf5lnI3m0Lpztj7OwGhtnXebnnCc84eHzvNSoFd8Z2mG80cllzULbTfpBwgpwesB4F4Q2xR+dPPjHi6UNmyDjEzvDlTMyJ/GjIw3wA45MMZNwVOy1P1ofeFZ336gy5NRG7hgQ/NywGw4dBOZsT1F+QDVDPd5bLKnEuPsBHNqpgEVsNtBa1hYWOIHb3i6EhYwlkgam0bxYwFwwfaYaJtST7onX5qZzqe2psx3TU5XyCaMUd0wsCwrhcvOao9iJ2a2mIyxPd2apWwSeFOWjA7e+5xJwrXlwWO6+Ly820Xi09QvRb10138YNLB+aXbytyMMO63Ojcl2B3kVlM+61XHY8HonMdh8DJPf7kYUI/WFqvkwR22jTLEdwFohsdsWPupkmEoHQWiJGq0TQqkZVdvyU8VNHc1dgeFV+cN9ycl/jw29x5+b2ewYmQuGb18r/CdOuoeZ4gOVC0Imb1/YQHtPi0ui5v6NVwnAQZtxFWm9v6hKsDe3NllrE7br5XYEk7JwOq333pFHg==
    admin-user: AgATC27srHlfzdYpfgp8YFapyteB50lWhQTRWxqXN5PApKff7qWOexhv36d0K0nWQJxCEU3hxbib0dSZzTGncqSaqaB6Zmwpu1qmiQECJ+iUC854rGYhltB/RRCRO0XDpLDRvm3pOWzpsSxLsp/4zgPxGexukCpJk968my9JZMMryCm/J2EVN9+JJvIUJRA+SUMl9p6ewWbK9DMAwYSy0zx/rF5mz9Zqms3LIPlyE7xxRTaiF+nzVkAJSWP+CeWGlg7gN3PW+een3oneHhPml9F8tK0wjef/FL8P4U89FmA6ovEymkqNjsP6q9+OlAyEQu6Jto10+DM1c2F4NRn+vG7aPbe95a2cFiRNQKejVAJ+Url9QbX6wcw67KoypZ8EztrfZ7Dar3B+w99jBBBa2q2Tsbh4ybID0fzkzgGMduHq19JHj0xtbVF/TXserqbBQy6rM5r5gU5txZlih8eq56TSqIAFzRu5Zt/PNHi07hkCzuT1UhVQ29UyfXrPGfJvX05udsPRukdGkXoO1HwHJQOS3OXY0gLC/QL7bmZfuLyq1A233+eHeOwSjsVlcP5x6BZhg+w0+LO+d3v9tJwREONipLKVm/tG5a1geRiv4eWWiK9ZJEjoKeLr/bNs/w+9/5kJSQFZz2ukGkuyYmsx6JXd0IDjYmRfe6TFOpwm56cozQCFhfYIP+aylnXp9yjxHgxQbF1eJQ==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
