---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pan-vault-dek
  namespace: cde
spec:
  encryptedData:
    PanCrypto__Dek: AgBQiH6CvQJ8to7T5AdF3HLFm2hPQzC7MaL/YsxNcctg7KTHwzb4rdVyr4O+FeyFLWYkm8ekTYWYkKfOoUJDGgSRSSEKR8jWyfHeQRoO20I9SPN1gqS5XVmfCp/cCLtxPyT4887Ipve4szt23NEztAW+Qm8NzGwEwhjAvx8KLfw8679gAMGWcNz7p5kz+m9hkrkNeplubnnBcEKUzIiNu7BuBtqHVCfrSSzryjUjQ+eZPQIA2CsHJrJIwCoKYW9EPPMNB67kFaHeeVmQVQsVUXNTpHx8+K7JJytA6TE7CXd+6dBsHJQUmodEOIPy/nhbz3fSklLzfCTRAUlNXB/B+Uz2J4PtegJGhvLki8nwKJYuix6PVwx/qBr2ibIGSJSFVDaREXU16n0ZMdxSEwX1AbYU3I4+eZghA3kc+aqrzXZDU05i5J30h5X23YM+8H69Hkf6PQJ3w+gH4kYoiGdPqlxfbUTNZY+P3wz2nMpXsUdeJvJc1YrPuNCFoton8rCPeR4QLGXL579JJPqz5NRpCa0dsn3JBZZNcleMMbKqDZ0O9HqSkYfjyZ0Sh/tMUrwkVggRHQDXRa0UfYEZbHsQMLu31nJ0IopvDiLiZ2ZsN80blVHmB1H+NU6SiXcvr1eea05HEqUk5AXGEnCOmfGxb36jqFb3q7UKE2hEDMUiSi0p2xxNNP4S0kwQLPnpsT6HWDPGJorWcHvcPgIMDTEb4604Qamnn+NS6Cj1PG8X47i5uJiLvUX4NGiLvZg9tw==
  template:
    metadata:
      name: pan-vault-dek
      namespace: cde
    type: Opaque
