apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pan-vault
  namespace: cde
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - pan-vault.local
      secretName: pan-vault-tls
  rules:
    - host: pan-vault.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pan-vault
                port:
                  number: 8080