apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pan-vault-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/emmanuelepp/pan-vault
    targetRevision: main
    path: gitops/secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: cde
  syncPolicy:
    automated:
      prune: true
      selfHeal: true